
app = "horizon-n8n"
primary_region = "fra"

[build]
  image = "docker.io/n8nio/n8n:latest"

[env]
  N8N_HOST = "horizon-n8n.fly.dev"
  N8N_PROTOCOL = "https"
  WEBHOOK_URL = "https://horizon-n8n.fly.dev/"
  N8N_PORT = "5678"
  N8N_METRICS = "true"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
