import mongoose from 'mongoose';

const WarrantySchema = new mongoose.Schema({
    artisan: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    chantier: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Chantier',
        required: true
    },
    // Snapshot of client data (in case Chantier changes, or just for ease)
    clientName: {
        type: String,
        required: true
    },
    clientPhone: {
        type: String
    },

    // Warranty Details Requested by Artisan
    startDate: {
        type: Date,
        required: true
    },
    duration: {
        type: String,
        required: true // e.g., "10 ans"
    },
    // Changed from simple string to array of dates
    maintenanceVisits: [{
        date: { type: Date, required: true },
        status: { type: String, default: 'pending', enum: ['pending', 'completed', 'missed'] },
        notes: String
    }],

    // Admin Fields
    status: {
        type: String,
        enum: ['pending', 'approved', 'rejected'],
        default: 'pending'
    },
    contractNumber: {
        type: String // Generated by Admin
    },
    coverageDetails: {
        type: String // Admin can edit the specific coverage text
    },
    adminNotes: {
        type: String
    },

}, { timestamps: true });

export default mongoose.models.Warranty || mongoose.model('Warranty', WarrantySchema);
